apiVersion: v1
kind: Service
metadata:
  name: service-redis
  namespace: openbanking
  labels:
    app.kubernetes.io/name: service-redis
    app.kubernetes.io/instance: service-redis
spec:
  ports:
  - port: 6379
  selector:
    app: service-redis
